### PR TITLE
PJ - getActiveQuarterList

### PR DESCRIPTION
**Pull request by PiyushJadhav**
the method is added successfully and does not reinvent anything, rather uses existing code to make the getActiveQuarterList() function.

Added the new controller endpoint as well.

Added testing for the new function and endpoint added that passes mutation testing and jacoco locally. 

dokku link: https://courses-pjadhav.dokku-04.cs.ucsb.edu

### CODE REVIEW

**Review by nilay-kundu — APPROVED** [review]
lgtm

**Review by pconrad — APPROVED** [review]
Code LGTM.. will test on dokku

**Comment by pconrad** [comment]
The linked dokku deployment is on commit 8559897 which is none of the commits in the PR.

And, the new endpoint isn't available on swagger on the deployed link:

image

**Comment by pconrad** [comment]
Comment from slack: https://ucsb-cs156-f24.slack.com/archives/C07NV8JN50F/p1732132954289619

image

**Pull request merged**
