### PR TITLE
the purge logs button correctly calls the delete all endpoint and deletes all jobs

### LINKED ISSUE #15: When the Purge Job Log button is clicked, the backend route is called and the job log is cleared out.
In this task, you will now have the button implemented in issue #14 call the delete all api implemented in #13.

See issue #9 for more details.

### PR DESCRIPTION
**Pull request by michaelhu88**
closes #15 

right after I click the red button, this is what the page looks like: 
Screenshot 2024-11-26 at 5 51 25 PM

https://courses-michaelhu88.dokku-04.cs.ucsb.edu/

### CODE REVIEW

**Comment by nikhilvyas109** [comment]
Code looks good to me. Add a screenshot and description.

**Review by raysujf — COMMENTED** [review]
As I mentioned in the previous PR, there's still an issue with testing the job page on Dokku.

**Review by pconrad — COMMENTED** [review]
Code LGTM, but for some reason, the frontend code on the dokku deployment is not working; the pages becomes unresponsive and none of the job launcher controls are working.

I'm looking at the dokku deployment to see if I can figure out what's going on.

**Comment by pconrad** [comment]
Works on localhost, and when deployed to a different dokku.  Not sure what was wrong with the original deployment.

**Pull request merged**
